[package]
name = "bitval"
version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
documentation.workspace = true

[dev-dependencies]
bitpack = {path = "../bitpack"}
