[package]
name = "bitpack"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
quote = "1.0.36"
syn = {version = "1.0.109", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.86"

[lib]
proc-macro = true