[package]
name = "bitpack"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = {version = "1.0.109", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.86"
bitval = {path = "../bitval"}

[lib]
proc-macro = true