name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Run this only on tag push after success of CI
    if: |
      github.event_name == 'workflow_run' && 
        github.event.workflow_run.conclusion == 'success' &&
        startsWith(github.event.workflow_run.head_branch, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Cargo registry and build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build
      run: cargo build --verbose
      
    - name: Publish crates
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        for crate in $(ls -d */ | grep -v 'target' | sed 's#/##'); do
          echo "Publishing crate $crate"
          cd $crate
          cargo publish --token $CARGO_REGISTRY_TOKEN
          cd ..
        done
