name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (v*.*.*)'
        required: true
        type: string
      tag_message:
        description: 'Message for the tag'
        required: true
        type: string

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const tag = '${{ inputs.tag_name }}';
          const msg = '${{ inputs.tag_message }}';
          await github.rest.git.createTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tag,
            sha: context.sha,
            message: msg,
          });
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${tag}`,
            sha: context.sha,
          });
